### PR TITLE
Bug/schedule page issue #71

### LINKED ISSUE #71: ❓Having problems with the scheduling page
I just tried to schedule an applet on the admin panel and this happened:

screen_recording

Whenever I try to access scheduling preferences or just hit save, the list of activities on the left side automatically changes to those from a different protocol I scheduled previously. Might be a problem with cache.

### PR DESCRIPTION
**Pull request by devbtech**
Fixed #71

### CODE REVIEW

File: src/Steps/SetUsers.vue [hunk 1]
```diff
@@ -17,7 +17,7 @@
       />
       <h1>Pending Invitations</h1>
       <pending-invite-table
-        key="componentKey"
+        key="componentKey1"
```
Comment (henryrossiter) [inline src/Steps/SetUsers.vue:20]: What is this for?

Comment (devbtech) [reply src/Steps/SetUsers.vue:20]: @henryrossiter  it occurred a warning/error due to duplication of key value.  Not serious problem though

**Review by henryrossiter — DISMISSED** [review]

**Review by henryrossiter — APPROVED** [review]
